### ISSUE TITLE
Setting a custom annotation on a service causes a template error

### ISSUE THREAD

**Issue by malmanzor** [pegasystems/pega-helm-charts#108]
**Describe the bug**

Running the helm template command with custom annotations causes the following error

> Error: YAML parse error on pega/templates/pega-tier-service.yaml: error converting YAML to JSON: yaml: line 8: did not find expected key

**To Reproduce**

1. Download and unpack the chart pega-1.2.6
2. Edit the web tier's service block in pega/values.yaml

```yaml
      service:
        # For help configuring the service block, see the Helm chart documentation
        # https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#service
        port: 80
        targetPort: 8080
       # customization:
        annotations:
          myannotation: "true" 
```
3. Render the template `helm template pega --values pega/values.yaml`

**Expected behavior**
The templates should render with the custom annotations set in the pega-web service

**Chart version**
pega-1.2.6 . No customizations besides the change to values.yaml noted above
helm version 3.0.2 on ubuntu linux
