### ISSUE TITLE
Specifying additional context.xml resource attributes

### ISSUE THREAD

**Issue by dcasavant** [pegasystems/pega-helm-charts#121]
**Is your feature request related to a problem? Please describe.**
Today the only way I can add custom attributes to the resource object in context.xml is to extend the Docker image or inject an entire context.xml.tmpl file.  I would rather make a minimal modification to the pega.yaml file and inject the attributes without overriding any configuration files. 

**Describe the solution you'd like**
I would like the ability to add [custom resource attributes in the context.xml file](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/config/deploy/context.xml.tmpl#L20) via injection. These could bee added via configuration in the pega.yaml file.  

Example:
```yaml
tier:
  name: "web"
  custom:
    resource-attribute:
      - name: "testOnBorrow"
        value: "true"
```

**Describe alternatives you've considered**
- Extend the Docker image.
- Override the context.xml.tmpl file.
