### ISSUE TITLE
Annotation customization

### ISSUE THREAD

**Issue by dcasavant** [pegasystems/pega-helm-charts#130]
**Is your feature request related to a problem? Please describe.**
I want the ability to add custom annotations to the Pod template as I would for an Ingress or Service object.

**Describe the solution you'd like**
I would like the ability to specify custom annotations in a list for each tier of the Helm chart.

Example:
```yaml
global:
  tier:
  - name: "web"
    pod-annotation:
      "com.example.custom/my-annotation": "value"
```

This should follow the same pattern used for ingress and service annotations.
