### ISSUE TITLE
Upgrading Issues (8.3.0 to 8.3.2)

### ISSUE THREAD

**Issue by brettcurtis** [pegasystems/pega-helm-charts#134]
**Describe the bug**
I'm trying to upgrade from 8.3.0 to 8.3.2 and having issues on the upgrade action. Documentation on exactly what I need to do isn't clear. Could be missing some steps not sure..

**To Reproduce**
1: Create new installer image based of the 8.3.2 binaries downloaded from Pega site
2: Pull 8.3.2 docker image for pega and search and publish to private repo
3: Configure installer upgrade action:
```yaml
# Pega Installer settings                                                                           
installer:
  image: "gcr.io/my-repo/pega-installer:48e448e4b656076f69a3d38e990d7929895f19b3"           #adminPassword: "YOUR_ADMIN_PASSWORD"                                                               # Upgrade specific properties
  upgrade:                                                                                              # Type of upgrade                                                                                   # Valid values are 'in-place' , 'out-of-place'
    upgradeType: "in-place"
    # Specify target rules schema for migration and upgrade
    targetRulesSchema: ""
```
4: Run helm:
```none
 helm upgrade pega pega/pega --namespace pega --values pega.yaml --set global.actions.execute="upgrade"
```

**Expected behavior**
pega-db-upgrade kubernetes job run successfully 

**Chart version**
1.2.7

**Server (if applicable, please complete the following information):**
 - Environment: [GKE]
 - Database: [PostgreSQL]

**Additional context**
first Exception I see:
```none
[java] Exception in thread "main" java.lang.NoSuchFieldError: REFLECTION
```
