### ISSUE TITLE
Support for BItnami sealed secrtes

### ISSUE THREAD

**Issue by dhanoa11** [pegasystems/pega-helm-charts#196]
Hi Team, does the Helm charts support Bitnami sealed secrets for passwords?

**Comment by zitikay** [comment]
Passwords are all read from the same location, so to use Bitnami SealedSecrets you must override the [_pega-credentials-secret.tpl](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/templates/_pega-credentials-secret.tpl) and remove the value you intend on replacing with the sealed secret. For example remove `DB_PASSWORD` looking like so:
```

{{- define "pegaCredentialsSecretTemplate" }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pegaCredentialsSecret" }}
  namespace: {{ .Release.Namespace }}
data:
  # Base64 encdoded username for connecting to the Pega DB
  DB_USERNAME: {{ .Values.global.jdbc.username | b64enc }}

 {{ if (eq (include "performDeployment" .) "true") }}
  # Base64 encdoded username for connecting to cassandra
  CASSANDRA_USERNAME: {{ .Values.dds.username | b64enc }}
  # Base64 encdoded password for connecting to cassandra
  CASSANDRA_PASSWORD: {{ .Values.dds.password | b64enc }}
  {{ range $index, $dep := .Values.global.tier}}
  {{ if and ($dep.pegaDiagnosticUser) (eq $dep.name "web") }}
  # Base64 encdoded username for a Tomcat user that will be created with the PegaDiagnosticUser role
  PEGA_DIAGNOSTIC_USER: {{ $dep.pegaDiagnosticUser | b64enc }}
  # Base64 encdoded password for a Tomcat user that will be created with the PegaDiagnosticUser role
  PEGA_DIAGNOSTIC_PASSWORD: {{ $dep.pegaDiagnosticPassword | b64enc }}
  {{ end }}
  {{ end }}
{{ end }}
type: Opaque
{{- end }}
```
And override the [pegaCredentialVolumeTemplate](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/templates/_helpers.tpl#L230-L238) with a projected volume so multiple secrets can get mounted to the same location:
```
{{- define "pegaCredentialVolumeTemplate" }}
- name: {{ template "pegaVolumeCredentials" }}
  projected:
    defaultMode: 420
    sources:
    - secret:
        name: {{ template "pegaCredentialsSecret" }}
    - secret:
        name: bitnami-db-password
{{- end}}
```
Making sure that the data in the referenced secret matches the one you removed in the first step. So in this example, the bitnami secret may look like
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitnami-db-password
  namespace: mynamespace
spec:
  encryptedData:
    DB_PASSWORD: ****ENCRYPTED VALUE****
```
