### ISSUE TITLE
OpenShift: upgrade action is not doing anything

### ISSUE THREAD

**Issue by je-munobia** [pegasystems/pega-helm-charts#289]
**Describe the bug**
I am attempting to perform an "upgrade" action with upgradeType set to "in-place". I expected a Job to start with a POD that executes the upgrade. The actual effect is that no job/pod is created. I was trying to find OpenShift examples, but the docs 
do not cover OpenShift. 

**To Reproduce**
1. Install 8.5.2 (works)
2. Deploy 8.5.2 (works)
3. Upgrade 8.5.3 (no output)

**Expected behavior**
I expected a Job to start with a POD that executes the upgrade. The actual effect is that no job/pod is created.

**Chart version**
pega-1.5.3 
No customizations to chart, only setting values.

**Server (if applicable, please complete the following information):**
 - OS: RHEL 7.9 (Where I run helm 3.5.0)
 - Environment: OpenShift 4.7.7
 - Database: PostgreSQL 11

**Additional context**
Command:
`helm upgrade coe-bat pega/pega -f charts/pega/values-postgresql-generic.yaml -f charts/pega/values-openshift-local-postgresql-coe-bat.yaml --set global.actions.execute=upgrade --set global.jdbc.username=pega --set global.jdbc.password=SomePwd --timeout 30m0s`

**_values-postgresql-generic:_**
```
---
global:
  provider: "openshift"

  jdbc:
    driverClass: "org.postgresql.Driver"
    dbType: "postgres"
    # Baked into a bespoke image
    driverUri: "file:///opt/pega/xyz/postgresql-42.2.20.jar"

    rulesSchema: "rules"
    dataSchema: "data"

  docker:
    registry:
      url: "pega-docker-cicd-local.repository.xyz.net"
      username: ""
      password: ""
    pega:
      imagePullPolicy: IfNotPresent

#  upgrade:
#    kube-apiserver:
#      serviceHost: ""
#      httpsServicePort: ""

pegasearch:
  # Not allowed in OpenShift - Invalid value: true: Privileged containers are not allowed
  # I assume that the image comes with a properly configured /etc/sysctl.conf, vm.max_map_count=262144
  # TODO: Check with Pega if and why search image would not come correctly configured and what I should do.
  set_vm_max_map_count: false

cassandra:
  enabled: false

hazelcast:
  enabled: false
```

**_values-openshift-local-postgresql-coe-bat:_**
```
---
global:
  deployment:
    name: coe-bat

  jdbc:
    url: "jdbc:postgresql://my-postgresql-postgresql-0.my-postgresql-headless:5432/pega"

  docker:
    pega:
      image: "pega-docker-cicd-local.repository.xyz.net/platform/postgresql_pega:8.5.3-210521-1"

  tier:
    - name: "all"
      nodeType: "Stream,BackgroundProcessing,WebUser,Search"

      service:
        port: 80
        targetPort: 8080
        serviceType: LoadBalancer

      replicas: 2
      pegaDiagnosticUser: "pega_admin"
      pegaDiagnosticPassword: "SomePwd"
      volumeClaimTemplate:
        resources:
          requests:
            storage: 5Gi

pegasearch:
  image: "pega-docker-cicd-local.repository.xyz.net/platform/search:8.5.3"

installer:
  image: "pega-docker-cicd-local.repository.xyz.net/platform/postgresql_installer:8.5.3-210521-1"
  adminPassword: "SomePwd"
  upgrade:
    upgradeType: "in-place"

```
