### ISSUE TITLE
Helm 3 - Deployment strategy with Stream tier

### ISSUE THREAD

**Issue by Emilio-Pega** [pegasystems/pega-helm-charts#37]
```
tier:
  - name: custom
    nodeType: Stream
    volumeClaimTemplate:
        resources:
          requests:
            storage: 5Gi
    deploymentStrategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
```

This fails because a Stream nodeType uses a StatefulSet under the covers which does not support a `strategy` element as defined here: https://github.com/pegasystems/pega-helm-charts/blob/754066f10ff423c218c1162265fb295f1eb0fed8/charts/pega/templates/_pega-deployment.tpl#L20

Helm 3 will barf with this setup.

There is no obvious documentation for this, nor is their any protection in the helm charts themselves.

Request that the addition of strategy be fixed to work with StatefulSets, by automatically ignoring -or- by doing the correct equivalent for StatefulSets (if one exists)
