### ISSUE TITLE
GKE Ingress

### ISSUE THREAD

**Issue by brettcurtis** [pegasystems/pega-helm-charts#42]
GKE ingress now support session based affinity, https://cloud.google.com/load-balancing/docs/backend-service#session_affinity

Is there a limitation with this and Pega still?

Also GKE has a managed certificate resource: https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs

So ideally we would just use Google to manage all that stuff for us and get rid of Traefik. Keep the deployment easier. If we can use ingress like I mention above let me know and I'll clone this repo and see if I can figure out the helm stuff.

**Comment by dcasavant** [comment]
@brettcurtis It is on the list and well prioritized.  It looks like we will probably get to it soon after the new year.

**Comment by brettcurtis** [comment]
Awesome! Anything I can do to help reach out!

**Comment by brettcurtis** [comment]
I'm unable to get this to work using this doc: https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#managing-certificates-in-google-cloud

Here is my values:
```yaml
 # Specify the Pega tiers to deploy
  tier:
    - name: "web"
      # Create a an interactive tier for web users.  This tier uses
      # the WebUser node type and will be exposed via a service to
      # the load balancer.
      nodeType: "WebUser"

      service:
        # Enter the domain name to access web nodes via a load balancer.
        #  e.g. web.mypega.example.com
        domain: "pega-k8s.my-domain.com"
        port: 80
        targetPort: 8080
        serviceType: "NodePort"

      ingress:
        domain: "pega-k8s.my-domain.com"
        tls:
          enabled: true
          useManagedCertificate: true
```

What am I missing??

**Comment by dcasavant** [comment]
@brettcurtis You seem to be missing the `ssl_annotation` section in the linked example.  Do you have that in your yaml file and maybe missed it in the copy-paste?  If not, you should add it according to the doc/example.

```yaml
ingress:
  domain: "web.dev.pega.io"
  tls:
    enabled: true
    useManagedCertificate: true
    ssl_annotation:
      kubernetes.io/ingress.global-static-ip-name: web-ip-address
```

**Comment by brettcurtis** [comment]
So I'm not using a static IP based on this: "Using a static IP address is not mandatory; if you do not use it, remove the annotation."  So is it required?

Another thing I noticed was with the domain value is being pulled from the service not ingress, I would expect to have this config:

```yaml
# Specify the Pega tiers to deploy
  tier:
    - name: "web"
      # Create a an interactive tier for web users.  This tier uses
      # the WebUser node type and will be exposed via a service to
      # the load balancer.
      nodeType: "WebUser"

      service:
        port: 80
        targetPort: 8080
        serviceType: "NodePort"

      ingress:
        domain: "pega-k8s.my-domain.com"
        tls:
          enabled: true
          useManagedCertificate: true
```
However the ingress doesn't get the domain name in this case.
