### ISSUE TITLE
Pega Web pod does not define port for TLS 8443 and no way to disable port 80

### ISSUE THREAD

**Issue by lenisha** [pegasystems/pega-helm-charts#433]
**Describe the bug**
enabled TLS for Tomcat POD based on latest (2.2.0) docs , the new service is mapping port 443 to targetPort 8443
but deployment does not define TLS port 8443 on the pod

There is also no way to disable port 80

**To Reproduce**
Steps to reproduce the behavior Update pega.yml for Tomcat TLS

```
 service:
        # For help configuring the service block, see the Helm chart documentation
        # https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#service
        port: 80
        targetPort: 8080
        type: CLusterIP
        annotations: 
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        
        tls:
          enabled: true
          keystore: ""
          keystorepassword: ""
          port: 443
          targetPort: 8443
          cacertificate: ""
          # set enabled=true, only if traefik addon chart is deployed and traefik is enabled
          traefik:
              enabled: false
              serverName: ""
              # set insecureSkipVerify=true, if the certificate verification has to be skipped
              insecureSkipVerify: true
```

Pod
```
Containers:                                                                                                                                               │
│   pega-web-tomcat:                                                                                                                                        │
│     Container ID:   containerd://bf36991bf0dd3a0438411a8279c996100664ac4d190a6e4e47cc628233b190d6                                                         │
│     Image:          acr60109.azurecr.io/pega-tomcatmssql861:latest                                                                                        │
│     Image ID:       acr60109.azurecr.io/pega-tomcatmssql861@sha256:47012d4d43a155ff9eb8b56b690864d046f98aaed746ed2ce34b051d10082ab1                       │
│     Port:           8080/TCP                                                                                                                              │
│     Host Port:      0/TCP                                                                                                                                 │
│     Ready:          True                                                                                                                                  │
```
Service

```
Name:                     pega-web                                                                                                                        │
│ Namespace:                pega                                                                                                                            │
│ Selector:                 app=pega-web                                                                                                                    │
│ Type:                     LoadBalancer                                                                                                                    │
│ LoadBalancer Ingress:     10.1.0.108                                                                                                                      │
│ Port:                     http  80/TCP                                                                                                                    │
│ TargetPort:               8080/TCP                                                                                                                        │
│ NodePort:                 http  31660/TCP                                                                                                                 │
│ Endpoints:                10.1.16.104:8080                                                                                                                │
│ Port:                     https  443/TCP                                                                                                                  │
│ TargetPort:               8443/TCP                                                                                                                        │
│ NodePort:                 https  31713/TCP                                                                                                                │
│ Endpoints:                10.1.16.104:8443                                                                                                                │
│ Session Affinity:         None                                                                                                                            │
│ External Traffic Policy:  Cluster           
```

**Expected behavior**
Expected pega-web deployment/pod expose port 8443 consumed by service

**Chart version**
2.2.0
