### ISSUE TITLE
Helm chart Certificates for Tomcat are in plain text in helm chart - integrate with K8S secret

### ISSUE THREAD

**Issue by lenisha** [pegasystems/pega-helm-charts#434]
**Describe the bug**
Certificates for Tomcat pod need to be provided inside Helm Chart values. For better security need to have reference to Secret created (for example by external secret operator from KeyVault)

**To Reproduce**
set pega.yml values

```
 service:
        # For help configuring the service block, see the Helm chart documentation
        # https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#service
        port: 80
        targetPort: 8080
        type: CLusterIP
        annotations: 
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        
        tls:
          enabled: true
          keystore: "fuewhfwueuifhwiuefhiwhefw"
          keystorepassword: "xxxxx"
          port: 443
          targetPort: 8443
          cacertificate: "xfewfwew"
          # set enabled=true, only if traefik addon chart is deployed and traefik is enabled

```

**Expected behavior**
Certificates loaded by Tomcat from Kubernetes secret

**Chart version**
2.2.0
