### ISSUE TITLE
Pega web service is created as LoadBalancer instead of ClusterIP

### ISSUE THREAD

**Issue by lenisha** [pegasystems/pega-helm-charts#435]
**Describe the bug**
Defined service for pega-web tier to be exposed as ClusterIP, but chart created LoadBalancer

**To Reproduce**
Pega.yml
```
 service:
        # For help configuring the service block, see the Helm chart documentation
        # https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#service
        port: 80
        targetPort: 8080
        type: ClusterIP
        annotations: 
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        
        tls:
          enabled: true
          keystore: ""
          keystorepassword: ""
          port: 443
          targetPort: 8443
          cacertificate: ""
          # set enabled=true, only if traefik addon chart is deployed and traefik is enabled
          traefik:
              enabled: false
              serverName: ""
              # set insecureSkipVerify=true, if the certificate verification has to be skipped
              insecureSkipVerify: true
```

Created
```
 k get svc -n pega
NAME                                 TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
pega-search                          ClusterIP      10.2.0.223   <none>        80/TCP                       18h
pega-search-transport          ClusterIP      None         <none>        80/TCP                       18h
pega-stream                          LoadBalancer   10.2.0.60    10.1.0.109    7003:30760/TCP               18h
pega-web                             LoadBalancer   10.2.0.170   10.1.0.108    80:31660/TCP,443:31713/TCP   18h
```

**Expected behavior**
pega-web service should have been created as "ClusterIP" type

**Chart version**
2.2.0
