### ISSUE TITLE
Tier level environment settings override

### ISSUE THREAD

**Issue by kishorv10** [pegasystems/pega-helm-charts#499]
**Is your feature request related to a problem? Please describe.**
In the current help charts, there is no way to set or override environment settings at the tier level. So that I can supply different configurations for different tier.s
**Describe the solution you'd like**
Have a configuration option in values.yaml at tier level like `.Values.tier[].env`, which can take a list of environment variable key:value pairs. 

**Additional context**
This requirement is originated from [PR-497](https://github.com/pegasystems/pega-helm-charts/pull/497). There is need to provide different cassandra configuration for different tiers.

**Comment by kishorv10** [comment]
@baylp2022 Feel free to further add any more points deem necessary.

**Comment by kishorv10** [comment]
Support is already available (not exposed for general use).  `Values.yaml` sample snippet,
```
      livenessProbe:
        port: 8081

      custom:
        env: 
        - name: CENV_KEY1
          value: CValue1
        - name: CENV_KEY2
          value: CValue2
```
