### ISSUE TITLE
Hazelcast credentials not exported correctly for subchart

### ISSUE THREAD

**Issue by sudeshjethoe** [pegasystems/pega-helm-charts#514]
**Describe the bug**
The *pegaCredentialVolumeTemplate* cannot be used for generating the credentials for the Hazelcast subchart.

**To Reproduce**
Fill in values.yaml for the pega/pega helm chart, using external secret for hazelcast.external_secret_name and render the Hazelcast Statefulset.

![image](https://user-images.githubusercontent.com/1734689/216963832-ff668b15-4c8a-4677-aed3-2c30d1444840.png)

**Expected behavior**
The statefulset should now have an entry referencing this secret:
![image](https://user-images.githubusercontent.com/1734689/216963563-00b2eb70-be08-46b2-8b4f-a0f1cc17c1c0.png)

**Chart version**
This is using chart version 2.8.0

**Additional context**
The template which generates the credentials: https://github.com/pegasystems/pega-helm-charts/blob/v2.8.0/charts/pega/templates/_helpers.tpl#L361

Cannot be used here to reference a variable in a higher level.

As a workaround this can be fixed by duplicating the value in the helm variables file
```
hazelcast:
  # this variable gets used for web and batch
  external_secret_name: "hazelcast-credentials-secret"
  # this variable gets used by hazelcast
  hazelcast:
    external_secret_name: "hazelcast-credentials-secret"
```
