### ISSUE TITLE
[questions] How could I get Pega system 8.8 images?

### ISSUE THREAD

**Issue by Kenzku** [pegasystems/pega-helm-charts#543]
Hello,

I am doing a PoC to deploy Pega system on EKS.

I created a PostgreSQL based RDS on AWS, and with EKS running in the same VPC in AWS

My struggle is mostly the configuration of the values.yaml file.

e.g.

```
# Pega Installer settings.
installer:
  image: "YOUR_INSTALLER_IMAGE:TAG"
  adminPassword: "ADMIN_PASSWORD"

# Hazelcast settings (applicable from Pega 8.6)
hazelcast:
  # Hazelcast docker image for platform version 8.6 through 8.7.x
  image: "YOUR_HAZELCAST_IMAGE:TAG"
  # Hazelcast docker image for platform version 8.8 and later
  clusteringServiceImage: "YOUR_CLUSTERING_SERVICE_IMAGE:TAG"
```

 I tried this command to install the Pega system as a helm release, without updating the installer image by hoping there was a default value:

```
helm install pega-demo pega/pega --namespace pega-demo --values ./values.yaml --set global.actions.execute=install-deploy
```

I got these problems, e.g. pods hanging at init stage, and looks like container "pega-installer" cannot get the installer image
```
pega-helm-charts % ks get pods
NAME                          READY   STATUS             RESTARTS   AGE
pega-batch-86bd6dc97b-ccwh2   0/1     Init:0/3           0          8m3s
pega-db-install-6sdps         0/1     InvalidImageName   0          8m2s
pega-demo-cassandra-0         1/1     Running            0          8m3s
pega-demo-cassandra-1         1/1     Running            0          5m52s
pega-demo-cassandra-2         1/1     Running            0          4m18s
pega-search-0                 1/1     Running            0          8m3s
pega-stream-0                 0/1     Init:0/3           0          8m3s
pega-web-7db75d4c84-jkppp     0/1     Init:0/3           0          8m3s


pega-helm-charts % ks logs pega-web-7db75d4c84-jkppp -c wait-for-pegainstall
[2023-03-23 14:31:55] Waiting for job pega-db-install...


pega-helm-charts % ks get jobs
NAME              COMPLETIONS   DURATION   AGE
pega-db-install   0/1           8m52s      8m52s


pega-helm-charts % ks logs jobs/pega-db-install
Error from server (BadRequest): container "pega-installer" in pod "pega-db-install-6sdps" is waiting to start: InvalidImageName
```

Based on the reference page: https://pegasystems.github.io/pega-helm-charts/docs/Deploying-Pega-on-EKS.html#installing-and-deploying-pega-platform-using-helm-charts--90-minutes

I tried to pull the docker image, but hit some authentication issues. now, based on the discussion here: https://github.com/pegasystems/pega-helm-charts/issues/166

```
pega-helm-charts % docker pull pega-docker.downloads.pega.com/platform/installer:8.8  
Error response from daemon: Head "https://pega-docker.downloads.pega.com/v2/platform/installer/manifests/8.8": unknown: Authentication is required
```

I was wondering, is there a pre-built free dev version of Pega installer 8.8 image available for PoC purpose? if yes, how I shall configure the value.yaml to continue from my side, and if not, what is the process to get the images, e.g. license, docker image pull secrets etc.
