### ISSUE TITLE
tier.service.domain variable from values.yaml not used?

### ISSUE THREAD

**Issue by PegaBasis** [pegasystems/pega-helm-charts#57]
Hello,

We are deploying Pega Helm charts in a OpenShift 3.11 cluster.
When we deploy an environment the value from tier.service.domain is used as the hostname in our route.
We have configured the following:
```yaml
      service:
        # Enter the domain name to access web nodes via a load balancer.
        #  e.g. web.mypega.example.com
        domain: "web.pega.{our domain}"
        port: 80
        targetPort: 8080
```

In our OpenShift cluster the following is configured:
```yaml
spec:
  host: pega-web-pega2.{our domain}
```

pega2 is the name of our OpenShift project (namespace).
So looks like OpenShift is generating its own hostname instead of the hostname configured in the values file.

Can you please check why this is happening?
