### ISSUE TITLE
SRS add support for setting securityContext

### ISSUE THREAD

**Issue by konire** [pegasystems/pega-helm-charts#711]
**Is your feature request related to a problem? Please describe.**
The SRS chart currently does not support setting the securityContext on pod or container. 

**Describe the solution you'd like**
I'd like to (optionally) set the securityContext. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by kishorv10** [comment]
@reddy-srinivas @ravitejamekapega Can you please take a look?

**Comment by dekke046** [comment]
@konire @kishorv10 @reddy-srinivas @ravitejamekapega,

Perhaps this can be looked at more generic.

I am facing customisations to the template files due to company security settings and therefore for all containers/pods I need to add the following:

```
  securityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
```

It would be great if these securityContext values can be specified in the `values.yaml`, so at the global level and be fully inherited by all underlying templates or charts.

Especially on in-company shared k8s platforms, security becomes more and more important.
