### ISSUE TITLE
Question on resource definition block in `values.yaml`

### ISSUE THREAD

**Issue by flo-kn** [pegasystems/pega-helm-charts#861]
Hi dear Pega Helm Chart team,

first happy new year and many thanks on the great work in this repo. 

In release [v3.22.0](https://github.com/pegasystems/pega-helm-charts/releases/tag/v3.22.0) we see an introduction of a new way to define resource request and limits/

E.g within a tier element like so:
```yaml
 resources:
    requests:
      memory: "8Gi"
      cpu: "50m"
    limits:
      memory: "8Gi"
      cpu: "50m"
```

...vs. flat with the old way. 

E.g like so
```yaml
cpuRequest: 50m
memRequest: "8Gi"
cpuLimit: 500m
memLimit: "8Gi"
```

Yet in the [README.md Managing resource section](https://github.com/vargm/pega-helm-charts/blob/master/charts/pega/README.md#managing-resources) we still see the old way documented. 

Does it mean both is still possible? Or what's the difference between both ways of defining resources in pega.

Would be very much appreciate a clarification or a pointer to an explanation. Many thx in advance. Cheers
