### ISSUE TITLE
Offer option to run pods with a non-default service account

### ISSUE THREAD

**Issue by rbogendoerfer** [pegasystems/pega-helm-charts#920]
**Is your feature request related to a problem? Please describe.**
Some compliance guidelines require that Kubernetes deployments are not using the default service account. An example of such compliance guideline is the German [APP.4.4,](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Grundschutz/IT-GS-Kompendium_Einzel_PDFs_2022/06_APP_Anwendungen/APP_4_4_Kubernetes_Edition_2022.pdf) which is used in the public sector. The requirement for the service account is described in paragraph APP.4.4.A9.

**Describe the solution you'd like**
Add a configuration option to create and use a specific service account, e.g.:
```
serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  name: pega-sa
```
The specified service account should be used in the pods instead of the default service account:
```
spec:
  serviceAccountName: {{ .root.Values.serviceAccount.name }}
```
Of course this is just a very simplified example to show the basic requirement.
